-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "discipline" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "content" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "bank" TEXT,
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
